<table align="left" width=100%>
    <tr>
        <td width="10%">
            <img src="in_class.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                    <b>Inclass - Lab<br> (Day 4)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

## Table of Content
1. **[User-Define Function](#User_Define)**
2. **[Lambda Functions](#Lambda_Functions)**
    - 2.1 [Map Function](#Map_Function)
    - 2.2 [Filter Function](#Filter_Function)
    - 2.3 [Reduce Function](#Reduce_Function)

### Let's begin with some hands-on practice exercises

<a id='User_Define'></a>
## 1. User-Define Function:

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Define the python function to swap first and last value of the given list<b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
my_list = [15, 78, 10, 45, 89]

In [3]:
# Write your code here
def swap_el(l):
    l[0],l[-1]=l[-1],l[0]
    return l
my_list = [15, 78, 10, 45, 89]
print(swap_el(my_list))

[89, 78, 10, 45, 15]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Define the python function which adds two global numeric variables (1204 and 344536)<b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [4]:
# Write your code here

def add_nums():
    return a+b

a=1204
b=344536
print(add_nums())
    

345740


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Define the python function to check whether the number 33 is even or odd<b>   
                </font>
            </div>
        </td>
    </tr>
</table>

In [6]:
# Write your code here
def eve_odd(num):
    ans='Even' if num%2==0 else 'Odd'
    return ans

print(eve_odd(33))

Odd


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Define the python function to calculate the factorial of the number<b>  
                </font>
            </div>
        </td>
    </tr>
</table>

In [12]:
# Write your code here
def factorial(n):
    if n==0 or n==1:
        return 1
    elif  n<0:
        return 'Invalid number'
    else:
        return n*factorial(n-1)
    
print( factorial(6))

720


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Define a function to add new items(1,2,3) in the empty list<b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [ ]:
def add_val(a):
    l=[]
    l.append(a)

In [13]:
# Write your code here
def add_el_list(*args):
    l=[]
    for i in args:
        l.append(i)
    return l

print(add_el_list(*(1,4,8,9,14,15,58)))

[1, 4, 8, 9, 14, 15, 58]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6.  Write a python function to test whether the two words start with the same character or not (take the inputs from the user)<b> 
                </font>
            </div>
        </td>
    </tr>
</table>

In [15]:
# Write your code here
def same_start(s1,s2):
    if s1[0].lower()==s2[0].lower():
        return 'Starting letters are same'
    else:
        return 'Satrting letters are different'
    
print(same_start(input(),input()))

bijali
raj
Satrting letters are different


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Check if the string contains a vowel or not (take the inputs from the user)</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [21]:
# Write your code here
def str_vowel(s):
    m=set('aeiou')
    if set(s.lower()).isdisjoint(m):
        return 'String not contain vowels'
    else:
        return 'String contain vowels'
    
print(str_vowel(input()))

bi
String contain vowels


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Write the python program to get the unique values from the given list<b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
my_list = [1,2,3,3,11,34,3,3,4,5]

In [23]:
# Write your code here
def unique_arr(arr):
    return set(arr)
my_list = [1,2,3,3,11,34,3,3,4,5]
print(unique_arr(my_list ))

{1, 2, 3, 34, 4, 5, 11}


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Find the common characters from the given two strings<b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the strings given below:**<br>
string1 = 'Angel'<br>
string2 = 'apple'

In [26]:
# Write your code here
string1 = 'Angel'      # assuming irrespective of case
string2 = 'apple'
def intersect(s1,s2):
    return set(s1.lower()).intersection(set(s2.lower()))

print(intersect(string1,string2))

{'a', 'l', 'e'}


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Define a function to perform addition, multiplication, and subtraction of the given two numbers<b> 
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the number given below:**<br>
a = 15<br>
b = 4

In [28]:
# Write your code here

def basic_math_func(a,b):
    a='Addition is: {}. Multiplication  is: {}. and substraction is: {}.'.format(a+b,a*b,a-b)
    return a

a = 15
b = 4
print(basic_math_func(a,b))

Addition is: 19. Multiplication  is: 60. and substraction is: 11.


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Define a function to find the sum of all elements in the list<b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
my_list = [34, 34, 55, 2, 56, 45]

In [29]:
# Write your code here
def addition(arr):
    return sum(arr)

my_list = [34, 34, 55, 2, 56, 45]
print(addition(my_list))

226


<a id='Lambda_Functions'></a>
## 2. Lambda Functions

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Find the minimum of the two numbers(34 and 78) using the lambda function<b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [30]:
# Write your code here
a=lambda x,y:min(x,y)
print(a(34,78))

34


<a id='Map_Function'></a>
### 2.1 Map Function

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Calculate the square of each element from the given tuple using the map function<b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the tuple given below:**<br>
number = (11, 21, 30, 34)

In [31]:
# Write your code here
number = (11, 21, 30, 34)
a=list(map(lambda x:x**2,number))
print(a)

[121, 441, 900, 1156]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Read the given sentence and print the length of each word in a sentence in a list using the map function<b>
                </font>
            </div>
        </td>
    </tr>
</table>

** Use the sentence given below:**<br>
sentence = 'Python for Data Science'

In [36]:
# Write your code here
sentence = 'Python for Data Science'
dict (zip( sentence.split(),list (map (len,sentence.split()))))

{'Python': 6, 'for': 3, 'Data': 4, 'Science': 7}

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Find the remainder of all the numbers present in a list after dividing by 5
<b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
numbers = [ 74, 85, 14, 23 ]

In [37]:
# Write your code here
numbers = [ 74, 85, 14, 23 ]
list(map(lambda x:x%5,numbers))

[4, 0, 4, 3]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Concatenate elements from the list1 with the corresponding element of list2<b>
                </font>
            </div>
        </td>
    </tr>
</table>

** Use the list given below:**<br>
list1 = ['I', 'felt', 'happy', 'because', 'I', 'saw', 'the', 'others', 'were', 'happy']<br>
list2 = [11,22,33,44,55,66,77,88,99]

In [39]:
# Write your code here
list1 = ['I', 'felt', 'happy', 'because', 'I', 'saw', 'the', 'others', 'were', 'happy']
list2 = [11,22,33,44,55,66,77,88,99]
ans=list(map(lambda x:str(x[0])+str(x[-1]),zip(list1,list2)))
print(ans)

['I11', 'felt22', 'happy33', 'because44', 'I55', 'saw66', 'the77', 'others88', 'were99']


<a id='Filter_Function'></a>
### 2.3 Filter Function

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Find the common elements from the given array using filter method<b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>
arr1 = ['t','u','t','o','r','i','a','l']<br>
arr2 = ['p','o','i','n','t']

In [41]:
# Write your code here
arr1 = ['t','u','t','o','r','i','a','l']
arr2 = ['p','o','i','n','t']

list(filter(lambda x: x in arr1,arr2))

['o', 'i', 't']

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Remove odd numbers from the given list<b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
numbers = [21, 23, 443, 355, 743, 823, 110, 1241, 3673, 352, 278, 37, 7]

In [42]:
# Write your code here
numbers = [21, 23, 443, 355, 743, 823, 110, 1241, 3673, 352, 278, 37, 7]
list(filter(lambda x: x%2==0,numbers))

[110, 352, 278]

<a id='Reduce_Function'></a>
### 2.4 Reduce Function

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Calculate the sum of the numbers from 1 to 100<b> 
                </font>
            </div>
        </td>
    </tr>
</table>

In [44]:
# Write your code here
from functools import reduce
reduce(lambda x,y:x+y,range(1,101))

5050

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>20. Determine the maximum of a given list using reduce function<b> 
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
my_list = [47,11,42,102,13]   

In [45]:
# Write your code here
my_list = [47,11,42,102,13]
reduce(lambda x,y:max(x,y),my_list)

102

In [1]:
np.array([1,2,3])

<IPython.core.display.Javascript object>

array([1, 2, 3])

In [5]:
# name=['Shivu']
# age=[23]
d={'Name':['Shivu'],'Age':[25]}
pd.DataFrame(d)

<IPython.core.display.Javascript object>

Name  Age
0  Shivu   25

In [6]:
m=np.array([78,56,47,89,52,63,57])
m

<IPython.core.display.Javascript object>

array([78, 56, 47, 89, 52, 63, 57])

In [8]:
m[m>68]

array([78, 89])

In [9]:
m//2

array([39, 28, 23, 44, 26, 31, 28], dtype=int32)

In [12]:
if any(m%2==0):
    print('yes')

yes


In [16]:
import random as r
r.randint(1,10)

3

In [20]:
np.random.randint(3,30,(2,2))

<IPython.core.display.Javascript object>

array([[25, 23],
       [14, 20]])

In [24]:
np.array({1,2})

<IPython.core.display.Javascript object>

array({1, 2}, dtype=object)

In [ ]:
c=1
p=30000
interest=p*4*(.1045)
while p>0 and interest>0:
    print(interest)
    interest=p*(1+(0.1045))
    print(interest)
    p=p+interest
    print(p)
    
    user=int(input())
    p-=user//2
    interest-=user//2
    print(p)
    print(interest)
    
    
    
    

12540.0
33135.0
63135.0
10000
58135.0
28135.0
28135.0
64210.107500000006
122345.10750000001
10000
117345.10750000001
59210.107500000006
59210.107500000006
129607.67123375002
246952.77873375005
10000
241952.77873375005
124607.67123375002
124607.67123375002
267236.84411142697
509189.622845177
10000
504189.622845177
262236.84411142697
262236.84411142697
556877.438432498
1061067.061277675
10000
1056067.061277675
551877.438432498
551877.438432498
1166426.069181192
2222493.130458867
50000
2197493.130458867
1141426.069181192
1141426.069181192
2427131.1625918187
4624624.293050686
80000
4584624.293050686
2387131.1625918187
2387131.1625918187
5063717.531674483
9648341.82472517
